openapi: "3.0.0"
info:
  version: 1.0.0
  title: scheduling tasks
  license:
    name: API created with educational purpose 
servers:
  - url: http://scheduling-tasks.swagger.io/v1
paths:
  /schedules:
    get:
      summary: List all availavable Schedules
      operationId: listSchedules
      tags:
        - Schedule
      parameters:
        - name: daysLimit
          in: query
          description: How many days to return at one time (max 30)
          required: false
          schema:
            type: integer
            format: int32
        - name: status
          in: query
          description: Filter by status
          required: false
          schema:
            $ref: "#/components/schemas/Status"
      responses:
        '200':
          description: A paged array of schedules
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ScheduleList"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create an Schedule
      tags:
        - Schedule      
      operationId: createSchedule
      requestBody:
        description: Create an Schedule
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Schedule"
        required: true
      responses:
        '201':
          description: Created with success
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                
  /schedules/{scheduleId}:
    get:
      summary: Info for a specific Schedule created
      operationId: showScheduleById
      tags:
        - Schedule
      parameters:
        - name: scheduleId
          in: path
          required: true
          description: The id of the schedule to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Schedule"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Status:
      type: string
      enum: [available, unavailable]
    Schedule:
      type: object
      required:
        - date
        - time
      properties:
        id:
          type: integer
          format: int64
        date:
          type: string
          format: date
        time:
          type: integer
          format: int64
        status:
          $ref: "#/components/schemas/Status"
    ScheduleList:
      type: array
      items: 
        $ref: "#/components/schemas/Schedule"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string